AFG:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/AFG/COVID/AFG_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
COD:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/COD/COVID/COD_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
SDN:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SDN/COVID/SDN_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
SSD:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SSD/COVID/SSD_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
SOM:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SOM/COVID/SOM_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  