AFG:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/AFG/COVID/AFG_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  #shape: 'https://github.com/OCHA-DAP/pa-COVID-model-reports/raw/master/Shapes/afg_admbnda_adm1_agcho_20180522/afg_admbnda_adm1_agcho_20180522.shp'
  shape: 'Shapes/afg_admbnda_adm1_agcho_20180522/afg_admbnda_adm1_agcho_20180522.shp'
  npi_admin1: 'Bucky_results/AFG_npi/adm1_quantiles.csv'
  country_iso2: 'AF'
COD:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/COD/COVID/COD_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  npi_admin1: 'Bucky_results/COD_npi/adm1_quantiles.csv'
SDN:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SDN/COVID/SDN_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  npi_admin1: 'Bucky_results/SDN_npi/adm1_quantiles.csv'
SSD:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SSD/COVID/SSD_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  npi_admin1: 'Bucky_results/SSD_npi/adm1_quantiles.csv'
SOM:
  subnational_cases_url: 'https://github.com/OCHA-DAP/pa-COVID-model-parameterization/raw/master/Outputs/SOM/COVID/SOM_COVID.csv'
  subnational_cases_source: 'Ministry of Public Health (subnational)'
  npi_admin1: 'Bucky_results/SOM_npi/adm1_quantiles.csv'
  